SET SESSION FOREIGN_KEY_CHECKS=0;


/* Create Tables */

CREATE TABLE EML_SEND
(
	ESNO int(10) NOT NULL AUTO_INCREMENT,
	ESTITLE varchar(50),
	ESTO varchar(50),
	ESCC varchar(1000),
	ESBCC varchar(1000),
	ESCONTENTS text,
	USERNO int(10) NOT NULL,
	PRIMARY KEY (ESNO),
	UNIQUE (ESNO)
);


CREATE TABLE EML_SENDFILE
(
	FILENO int(10) NOT NULL AUTO_INCREMENT,
	FILENAME varchar(100),
	REALNAME varchar(30),
	FIELSIZE int(10),
	ESNO int(10) NOT NULL,
	PRIMARY KEY (FILENO),
	UNIQUE (FILENO),
	UNIQUE (ESNO)
);


CREATE TABLE SCH_DETAIL
(
	SSNO int(10) NOT NULL,
	SDSEQ smallint NOT NULL,
	SDDATE date,
	SDHOUR char(2),
	SSMINUTE char(2),
	PRIMARY KEY (SSNO, SDSEQ),
	UNIQUE (SSNO),
	UNIQUE (SDSEQ)
);


CREATE TABLE SCH_SCHEDULE
(
	SSNO int(10) NOT NULL AUTO_INCREMENT,
	SSTITLE varchar(50),
	SSTYPE char(1),
	SSSTARTDATE char(10),
	SSSTARTHOUR char(2),
	SSSTARTMINUTE char(2),
	SSENDDATE varchar(10),
	SSENDHOUR char(2),
	SSENDMINUE char(2),
	SSREPEATTYPE char(1),
	SSREPEATEND varchar(10),
	SSCONTENTS text,
	SSISOPEN char(1),
	UPDATEDATE datetime,
	INSERTDATE datetime,
	USERNO int(10) NOT NULL,
	PRIMARY KEY (SSNO),
	UNIQUE (SSNO)
);


CREATE TABLE SGN_DOC
(
	DOCNO bigint NOT NULL AUTO_INCREMENT,
	DOCTITLE varchar(50),
	DOCCONTENTS text,
	DELETEFLAG char(1),
	DOCSTATUS char(1),
	DOCSTEP smallint,
	DTNO int NOT NULL,
	UPDATEDATE datetime,
	INSERTDATE datetime,
	USERNO int(10) NOT NULL,
	DEPTNM varchar(20),
	DOCSIGNPATH varchar(200),
	PRIMARY KEY (DOCNO),
	UNIQUE (DOCNO),
	UNIQUE (DTNO)
);


CREATE TABLE SGN_DOCFILE
(
	FILENO int(10) NOT NULL AUTO_INCREMENT,
	FILENAME varchar(100),
	REALNAME varchar(30),
	FIELSIZE int(10),
	DOCNO bigint NOT NULL,
	PRIMARY KEY (FILENO),
	UNIQUE (FILENO),
	UNIQUE (DOCNO)
);


CREATE TABLE SGN_DOCTYPE
(
	DTNO int NOT NULL AUTO_INCREMENT,
	DTTITLE varchar(30),
	DTCONTENTS text,
	DELETEFLAG char(1),
	PRIMARY KEY (DTNO),
	UNIQUE (DTNO)
);


CREATE TABLE SGN_PATH
(
	SPNO int NOT NULL AUTO_INCREMENT,
	SPTITLE varchar(30),
	INSERTDATE date,
	USERNO int(10) NOT NULL,
	SPSIGNPATH varchar(200),
	PRIMARY KEY (SPNO),
	UNIQUE (SPNO)
);


CREATE TABLE SGN_PATHUSER
(
	SPNO int NOT NULL,
	SPUSEQ int NOT NULL,
	USERNO int(10) NOT NULL,
	SSTYPE char(1),
	PRIMARY KEY (SPNO, SPUSEQ),
	UNIQUE (SPNO)
);


CREATE TABLE SGN_SIGN
(
	SSNO int(10) NOT NULL AUTO_INCREMENT,
	DOCNO bigint NOT NULL,
	SSSTEP smallint,
	SSTYPE char(1),
	SSRESULT char(1),
	SSCOMMENT varchar(1000),
	RECEIVEDATE datetime,
	SIGNDATE datetime,
	USERNO int(10) NOT NULL,
	PRIMARY KEY (SSNO),
	UNIQUE (SSNO),
	UNIQUE (DOCNO)
);



